#!/usr/bin/env ruby

if system("which rvm > /dev/null")
  cmd = "rvm default do ruby -rrubygems "
elsif system("which rbenv > /dev/null")
  cmd = "rbenv exec ruby -rrubygems "
else
  cmd = "ruby -rrubygems "
end

if !system("#{cmd} -rxcode-yamlizer -e '' 2> /dev/null")
  $stderr.puts "xcode-yamlizer: WARNING: Skipping checks because xcode-yamlizer the  gem is not installed. (Did you change your Ruby version?)"
  exit(0)
end

cmd << %Q{-e "require 'xcode-yamlizer'; XcodeYamlizer.run_post_merge"}

exit(system(cmd) ? 0 : 1)
